# Generated by Django 6.0 on 2026-01-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=150)),
                ('confirm_password', models.CharField(max_length=150)),
            ],
        ),
    ]
