# Generated by Django 5.2.8 on 2026-01-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
