# Generated by Django 4.2.7 on 2026-01-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_userpayment_stripe_checkout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='has_paid',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='stripe_checkout_id',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='stripe_product_id',
        ),
    ]
