# Generated by Django 4.2.7 on 2026-01-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_userpayment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpayment',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='stripe_customer_id',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpayment',
            name='stripe_product_id',
            field=models.CharField(default='INR', max_length=255),
            preserve_default=False,
        ),
    ]
