# Generated by Django 5.2.8 on 2026-01-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'OUT of Stock')], max_length=20)),
                ('product_types', models.CharField(choices=[('electronics', 'Electronics'), ('grocery', 'Grocery'), ('clothing', 'Clothing'), ('fitness', 'Fitness'), ('toys', 'Toys')], max_length=20)),
                ('vendor_name', models.CharField(max_length=150)),
            ],
        ),
    ]
