# Generated by Django 6.0 on 2026-01-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('IN STOCK', 'In stock'), ('OUT OF STOCK', 'Out of stock')], max_length=20)),
                ('product_types', models.CharField(choices=[('electronics', 'Electronics'), ('grocery', 'Grocery'), ('clothing', 'Clothing')], max_length=20)),
                ('vendor_name', models.CharField(max_length=150)),
            ],
        ),
    ]
