# Generated by Django 6.0 on 2026-01-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_types',
            field=models.CharField(choices=[('Electronics', 'ELECTRONICS'), ('Grocery', 'GROCERY'), ('Clothing', 'CLOTHING'), ('Fitness', 'FITNESS'), ('Toys', 'TOYS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('In stock', 'IN STOCK'), ('Out of stock', 'OUT OF STOCK')], max_length=20),
        ),
    ]
