# Generated by Django 6.0 on 2026-01-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_products', '0002_alter_products_product_types_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_types',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('grocery', 'Grocery'), ('clothing', 'Clothing'), ('fitness', 'Fitness'), ('toys', 'Toys')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'OUT of Stock')], max_length=20),
        ),
    ]
