# Generated by Django 5.2.8 on 2026-01-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_products', '0002_products_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=150),
        ),
    ]
