# Generated by Django 4.2.27 on 2026-01-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_products', '0004_alter_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
