# Generated by Django 4.2.27 on 2026-01-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_products', '0005_products_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='images',
            new_name='image',
        ),
    ]
