# Generated by Django 4.2.7 on 2026-01-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_products', '0008_products_currency_products_has_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stripe_product_id',
        ),
    ]
