# Generated by Django 4.2.7 on 2026-01-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_products', '0009_remove_products_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='products',
            name='has_paid',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stripe_checkout_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stripe_customer_id',
        ),
    ]
